<?php

namespace Hypebeast\WordpressBundle\Tests\Wordpress;

use Hypebeast\WordpressBundle\Wordpress\ApiAbstraction;

/**
 * Test class for ApiAbstraction.
 * Generated by PHPUnit on 2011-10-03 at 12:42:44.
 * 
 * @covers Hypebeast\WordpressBundle\Wordpress\ApiAbstraction
 */
class ApiAbstractionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ApiAbstraction
     */
    protected $object;
    
    protected $apiLoader;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $apiLoader = $this->getMockBuilder('Hypebeast\\WordpressBundle\\Wordpress\\ApiLoader')
                ->disableOriginalConstructor()->getMock();
        $apiLoader->expects($this->once())->method('load');
        
        $this->object = new ApiAbstraction($apiLoader);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testCallRunsFunction() {
        $function = 'Hypebeast\\WordpressBundle\\Tests\\Wordpress\\mockGlobalFunction';
        $this->assertEquals(mockGlobalFunction(), $this->object->$function());
    }
    
    public function testCallPassesArgumentsToFunction() {
        $function = 'Hypebeast\\WordpressBundle\\Tests\\Wordpress\\mockGlobalFunction';
        $this->assertEquals(mockGlobalFunction('1', '2'), $this->object->$function('1', '2'));
    }

}

function mockGlobalFunction($arg1='', $arg2='') {
    return "function was called with {$arg1} {$arg2}";
}

?>
