<?php

namespace Hypebeast\WordpressBundle\Tests\Utilities;

use Hypebeast\WordpressBundle\Utilities\RoleUtilities;

/**
 * Test class for RoleUtilities.
 * Generated by PHPUnit on 2011-10-09 at 19:00:32.
 */
class RoleUtilitiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testNormaliseRoleNames()
    {
        $this->assertEquals(
                array('ROLE_WP_A', 'ROLE_WP_B'),
                RoleUtilities::normalise_role_names(array('a', 'b'))
        );
        
        $this->assertEquals(
                array('PRE-A-SUF', 'PRE-B-SUF'),
                RoleUtilities::normalise_role_names(array('a', 'b'), 'pre-', '-suf')
        );
    }

}

?>
