<?php

namespace Hypebeast\WordpressBundle\Tests\DependencyInjection;

use Hypebeast\WordpressBundle\DependencyInjection\HypebeastWordpressExtension;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Yaml\Parser;

/**
 * Test class for HypebeastWordpressExtension.
 * Generated by PHPUnit on 2011-09-28 at 12:14:01.
 */
class HypebeastWordpressExtensionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HypebeastWordpressExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HypebeastWordpressExtension;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @expectedException \Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
     */
    public function testLoadRequiresWordpressUrl() {
        $config = $this->mockConfig();
        unset($config['wordpress_url']);
        $this->object->load(array($config), new ContainerBuilder);
    }

    /**
     * @expectedException \Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
     */
    public function testLoadRequiresNotEmptyWordpressUrl() {
        $config = $this->mockConfig();
        $config['wordpress_url'] = '';
        $this->object->load(array($config), new ContainerBuilder);
    }

    /**
     * @expectedException \Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
     */
    public function testLoadRequiresLoggedInKey() {
        $config = $this->mockConfig();
        unset($config['logged_in_key']);
        $this->object->load(array($config), new ContainerBuilder);
    }

    /**
     * @expectedException \Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
     */
    public function testLoadRequiresNotEmptyLoggedInKey() {
        $config = $this->mockConfig();
        $config['logged_in_key'] = '';
        $this->object->load(array($config), new ContainerBuilder);
    }

    /**
     * @expectedException \Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
     */
    public function testLoadRequiresLoggedInSalt() {
        $config = $this->mockConfig();
        unset($config['logged_in_salt']);
        $this->object->load(array($config), new ContainerBuilder);
    }

    /**
     * @expectedException \Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
     */
    public function testLoadRequiresNotEmptyLoggedInSalt() {
        $config = $this->mockConfig();
        $config['logged_in_salt'] = '';
        $this->object->load(array($config), new ContainerBuilder);
    }

    /**
     * Mock configuration values for testing
     *
     * @return array
     */
    protected function mockConfig() {
        $yaml = <<<EOF
wordpress_url: http://foobar
logged_in_key: foobar2000
logged_in_salt: NaCl
EOF;

        $parser = new Parser();
        return $parser->parse($yaml);
    }

}

?>
