<?php

namespace Hypebeast\WordpressBundle\Tests\Security\Http\Logout;

use Hypebeast\WordpressBundle\Security\Http\Logout\WordpressLogoutHandler;

/**
 * Test class for WordpressLogoutHandler.
 * Generated by PHPUnit on 2011-10-10 at 15:15:44.
 * 
 * @covers Hypebeast\WordpressBundle\Security\Http\Logout\WordpressLogoutHandler
 */
class WordpressLogoutHandlerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var WordpressLogoutHandler
     */
    protected $object;
    
    /**
     *
     * @var Hypebeast\WordpressBundle\Wordpress\ApiAbstraction
     */
    protected $api;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->api = $this->getMockBuilder('Hypebeast\\WordpressBundle\\Wordpress\\ApiAbstraction')
                ->disableOriginalConstructor()->setMethods(array('wp_logout'))->getMock();
        
        $this->object = new WordpressLogoutHandler($this->api);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function testLogoutLogsUserOutOfWordpress()
    {
        $this->api->expects($this->once())->method('wp_logout');
        
        $this->object->logout(
                $this->getMock('Symfony\\Component\\HttpFoundation\\Request'),
                $this->getMock('Symfony\\Component\\HttpFoundation\\Response'),
                $this->getMockForAbstractClass(
                    'Symfony\\Component\\Security\\Core\\Authentication\\Token\\AbstractToken')
        );
    }

}

?>
