<?php

namespace Hypebeast\WordpressBundle\Tests\Security\Authentication\Token;

use Hypebeast\WordpressBundle\Security\Authentication\Token\WordpressCookieToken;
use Hypebeast\WordpressBundle\Model\WordpressUser;

require_once __DIR__ . '/../../../WpUserMock.php';

/**
 * Test class for WordpressCookieToken.
 * Generated by PHPUnit on 2011-10-02 at 17:54:17.
 * 
 * @covers Hypebeast\WordpressBundle\Security\Authentication\Token\WordpressCookieToken
 */
class WordpressCookieTokenTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WordpressCookieToken
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WordpressCookieToken;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @expectedException \LogicException
     */
    public function testSetAuthenticatedToTrueThrowsException() {
        $this->object->setAuthenticated(true);
    }
    
    public function testConstructorWithUserMarksTokenAsAuthenticated() {
        $user = new WordpressUser;
        $user->roles = array('user');
        
        $token = new WordpressCookieToken($user);
        $this->assertTrue($token->isAuthenticated());
    }
    
    public function testConstructorWithoutRolesMarksTokenAsUnauthenticated() {
        $this->assertFalse($this->object->isAuthenticated());
    }

}